### ISSUE TITLE
请问是否有yandex浏览器可用的mobileconfig文件，以禁用自己安装扩展的通知？

### ISSUE THREAD

**Issue by chenxiccc** [tofuliang/MacAppKeys#1]
你好：

参考这个帖子 https://hencolle.com/2016/10/16/baidu_exporter/ 。成功解决了chrome浏览器下自己安装的扩展的每次启动chrome时的通知。
yandex是一款很好用的浏览器，同样可以使用chrome扩展，不知是否有Mac系统上可用的mobileconfig文件，使得无需每次启动浏览器时需要单独启用自己安装的扩展？

**Comment by tofuliang** [comment]
没有用过 yandex ,如果是基于chromium 内核的,可以参考官方文档生成配置,自行用 [mcxToProfile](https://github.com/timsutton/mcxToProfile) 转换成mobileconfig
